<a href="https://colab.research.google.com/github/kiminonawa1305/machine_learning/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1.1

In [8]:
amount = int(input("Nhập vào tổng số lượng số bạn muốn nhập: "))
print(f'Tổng số lượng phần tử muốn nhập là: {amount} phẩn tử.')
array = []
for index in range(amount):
    array.append(int(input(f'Số thứ {index + 1}: ')))

print(array)

maxArray = max(array)
minArray = min(array)
sumArray = sum(array)

#Sắp xếp mảng
array.sort()

print(f'Phần tử lớn nhất trong mảng là: {maxArray}')
print(f'Phần tử nhỏ nhất trong mảng là: {minArray}')
print(f'Tổng giá trị các phần có trong mảng là: {sumArray}')
print(f'Danh sách đã được sắp xết {array}')

totalPositive = 0
totalNegative = 0
for nunber in array:
    if nunber < 0:
        totalNegative += 1
    elif nunber > 0:
        totalPositive += 1

print(f'Tổng số âm trong mảng: {totalNegative} số')
print(f'Tổng số dương trong mảng: {totalPositive} số')

Nhập vào tổng số lượng số bạn muốn nhập: 5
Tổng số lượng phần tử muốn nhập là: 5 phẩn tử.
Số thứ 1: -1
Số thứ 2: 3
Số thứ 3: -7
Số thứ 4: 8
Số thứ 5: -10
[-1, 3, -7, 8, -10]
Phần tử lớn nhất trong mảng là: 8
Phần tử nhỏ nhất trong mảng là: -10
Tổng giá trị các phần có trong mảng là: -7
Danh sách đã được sắp xết [-10, -7, -1, 3, 8]
Tổng số âm trong mảng: 3 số
Tổng số dương trong mảng: 2 số


Task 1.2

In [9]:
def multiplication_n_number(n=1):
    if n == 1:
        return 1
    else:
        return n * multiplication_n_number(n - 1)


def sum_multiplication_n_number(n=1):
    if n == 1:
        return 1
    else:
        return multiplication_n_number(n) + sum_multiplication_n_number(n - 1)


print(sum_multiplication_n_number(7))

5913


Task 1.3

In [13]:
import datetime as dt

class Account:
    def __init__(self, name, email, country, friends, posts) -> None:
        self.name = name
        self.email = email
        self.country = country
        self.friends = friends
        self.posts = posts

    def get_max_like_post_by_friend(self):
        if len(self.friends) == 0:
            return None
        self.friends.sort(key=lambda friend: friend.__get_max_like_by_post(), reverse=True)
        return self.friends[0]

    def __get_max_like_by_post(self):
        if len(self.posts) == 0:
            return 0
        self.posts.sort(key=lambda post: post.likes, reverse=True)
        return self.posts[0].likes

    def has_more_10_posts(self):
        if len(self.posts) < 10:
            return False
        else:
            return True

    def __str__(self) -> str:
        friends_str = "; ".join(str(friend) for friend in self.friends)
        posts_string = "; ".join(str(post) for post in self.posts)
        return f'Name: {self.name}, email: {self.email}, country: {self.country}, friends: {friends_str}, post: {posts_string}, max_like_post: {self.__get_max_like_by_post()}'


class AccountManager:
    def __init__(self, accounts):
        self.accounts = accounts

    def group_accounts_by_post_like(self):
        result = {True: [], False: []}
        for account in self.accounts:
            if account.has_more_10_posts():
                result[True].append(account)
            else:
                result[False].append(account)
        return result

    def filter_accounts(self, country):
        result = [account for account in self.accounts if account.country == country]
        result.sort(key=lambda account: (-len(account.posts), account.name), reverse=False)
        return result

    def __str__(self) -> str:
        accounts_str = ";\n".join(str(account) for account in self.accounts)
        return f'accounts: {accounts_str}'


class Post:
    def __init__(self, content, subject, likes):
        self.content = content
        self.subject = subject
        self.likes = likes

    def __str__(self) -> str:
        return f'content: {self.content}, subject: {self.subject}, likes: {self.likes}'


class VerifiedAccount(Account):
    def __init__(self, name, email, country, friends, posts, from_date) -> None:
        super().__init__(name, email, country, friends, posts)
        self.from_date = from_date

    def __str__(self) -> str:
        return super().__str__() + " " + self.from_date.strftime("%c")


class NormalProduct(Account):
    def __init__(self, name, email, country, friends, posts) -> None:
        super().__init__(name, email, country, friends, posts)

    def __str__(self) -> str:
        return super().__str__()

In [14]:
print("oke")
post1 = Post("content 1", "subject 1", 10)
post2 = Post("content 2", "subject 1", 2)
post3 = Post("content 3", "subject 1", 12)

post4 = Post("content 4", "subject 2", 2)
post5 = Post("content 5", "subject 2", 9)
post6 = Post("content 6", "subject 2", 20)
post7 = Post("content 7", "subject 2", 20)

post8 = Post("content 8", "subject 3", 12)
post9 = Post("content 9", "subject 3", 30)
post10 = Post("content 10", "subject 3", 20)

posts1 = [post1, post2, post3]
posts2 = [post4, post5, post6, post7]
posts3 = [post8, post9, post10]

friend1 = Account("Name 1", "email 1", "country 1", [], posts1)
friend2 = Account("Name 2", "email 2", "country 1", [], posts2)
friend3 = Account("Name 3", "email 3", "country 2", [], posts3)

friends = [friend1, friend2, friend3]

account1 = Account("Name 1", "email 1", "country 1", friends, posts1)
account2 = Account("Name 2", "email 2", "country 1", friends, posts2)
account3 = Account("Name 3", "email 3", "country 1", friends, posts3)

account4 = NormalProduct("NormalProduct 1", "email 4", "country 1", friends, posts1)

account5 = VerifiedAccount("VerifiedAccount 1", "email 5", "country 1", friends, posts2, dt.datetime(2003, 5, 13))

accounts = [account1, account2, account3, account4, account5]

accountManager = AccountManager(accounts)

print(f'Max like posts by friends: {account1.get_max_like_post_by_friend()}')

for key, accounts in accountManager.group_accounts_by_post_like().items():
    accounts_str = ";\n".join(str(account) for account in accounts)
    print(f'key: {key}, accounts: \n{accounts_str}')

print("filter accounts")
for account in accountManager.filter_accounts("country 1"):
    print(f'account: {account}')


oke
Max like posts by friends: Name: Name 3, email: email 3, country: country 2, friends: , post: content: content 9, subject: subject 3, likes: 30; content: content 10, subject: subject 3, likes: 20; content: content 8, subject: subject 3, likes: 12, max_like_post: 30
key: True, accounts: 

key: False, accounts: 
Name: Name 1, email: email 1, country: country 1, friends: Name: Name 3, email: email 3, country: country 2, friends: , post: content: content 9, subject: subject 3, likes: 30; content: content 10, subject: subject 3, likes: 20; content: content 8, subject: subject 3, likes: 12, max_like_post: 30; Name: Name 2, email: email 2, country: country 1, friends: , post: content: content 6, subject: subject 2, likes: 20; content: content 7, subject: subject 2, likes: 20; content: content 5, subject: subject 2, likes: 9; content: content 4, subject: subject 2, likes: 2, max_like_post: 20; Name: Name 1, email: email 1, country: country 1, friends: , post: content: content 3, subject: s

Task 2

In [3]:
import numpy as np

Task 2.1

In [21]:
array = np.arange(25, 10, -1, dtype=int)
print(array)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11]


Task 2.2

In [8]:
array1 = np.array([1, 2, 3, 4])
print(array1)

[1 2 3 4]


In [9]:
array2 = np.tile(array1, 2)
print(array2)

[1 2 3 4 1 2 3 4]


In [10]:
array3 = np.tile(array1, 3)
print(array3)

[1 2 3 4 1 2 3 4 1 2 3 4]


Task 2.3

In [31]:
array_2D = np.random.randint(100, size=(3, 3)) * 0.01
print(array_2D)

[[0.55 0.7  0.21]
 [0.26 0.13 0.85]
 [0.46 0.3  0.55]]


In [33]:
array_2D[array_2D > 0.5] = 0.5
print(array_2D)

[[0.5  0.5  0.21]
 [0.26 0.13 0.5 ]
 [0.46 0.3  0.5 ]]
